services:
  - type: web
    name: tea-dealer-backend
    runtime: docker
    dockerfilePath: tea-dealer-backend/Dockerfile
    dockerContext: tea-dealer-backend
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
